const List<String> ppvOptions = [
  'Royal Rumble',
  'Elimination Chamber',
  'Fastlane',
  'WrestleMania',
  'Backlash',
  'Money in the Bank',
  'SummerSlam',
  'Payback',
  'Extreme Rules',
  'Survivor Series',
  'TLC: Tables, Ladders & Chairs',
  'King of the Ring',
  'No Way Out',
  'No Mercy',
  'Armageddon',
  'Judgment Day',
  'Vengeance',
  'Unforgiven',
  'Hell in a Cell',
  'Night of Champions',
  'Over the Limit',
  'Great Balls of Fire',
  'Clash of Champions',
  'Battleground',
  'Roadblock',
  'In Your House'
];
