const List<String> ppvOptions = [
  'Armageddon',
  'Backlash',
  'Battleground',
  'Clash of Champions',
  'Elimination Chamber',
  'Extreme Rules',
  'Fastlane',
  'Great Balls of Fire',
  'Hell in a Cell',
  'In Your House',
  'Judgment Day',
  'King of the Ring',
  'Money in the Bank',
  'Night of Champions',
  'No Mercy',
  'No Way Out',
  'Over the Limit',
  'Payback',
  'Roadblock',
  'Royal Rumble',
  'SummerSlam',
  'Survivor Series',
  'TLC',
  'Unforgiven',
  'Vengeance',
  'WrestleMania',
];
